services:
  aiimage-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: aiimage-next-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
    command: npm run dev
    networks:
      - aiimage-dev-network

networks:
  aiimage-dev-network:
    driver: bridge
