services:
  aiimage-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aiimage-next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - aiimage-network

networks:
  aiimage-network:
    driver: bridge
